# Generated by Django 3.0.7 on 2020-08-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0004_auto_20200827_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sumitaimodel',
            old_name='chat',
            new_name='houseName',
        ),
    ]
