# Generated by Django 3.0.7 on 2020-08-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0005_auto_20200827_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='userName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
