# Generated by Django 3.0.7 on 2020-08-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0006_chatmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='chat',
            field=models.TextField(null=True),
        ),
    ]
