# Generated by Django 3.0.7 on 2020-08-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0007_auto_20200830_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumitaimodel',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
