# Generated by Django 3.0.7 on 2020-09-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0011_auto_20200903_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumitaimodel',
            name='push',
            field=models.CharField(blank=True, default='b', max_length=100, null=True),
        ),
    ]
