# Generated by Django 3.0.7 on 2020-09-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0012_sumitaimodel_push'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sumitaimodel',
            old_name='push',
            new_name='pushuser',
        ),
    ]
