# Generated by Django 3.0.7 on 2020-09-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumitai', '0014_auto_20200904_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sumitaimodel',
            name='pushuser',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
